name: hello world

on:
  pull_request:
    branches:
      - main

jobs:
  say-hello:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout-code
      uses: action/checkout@v2

   - name: Gretings
      run: echo "Hello Marco"
