name: hello world

on:
  pull_request:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout-code
        uses: actions/checkout@v2

      - name: Docker-create
        run: docker build -t "docker-image-app" -f Dockerfile.dev .

      - name: Docker-container-with-lint
        run: docker run --rm docker-image-app npm run lint

<<<<<<< HEAD
     
=======
      # - name: Stop and remove the container
      #   run: |
      #     docker stop my-app-container
      #     docker rm my-app-container
>>>>>>> 4975f9f0a96ba8f21fc8213f05a535b16fef1d33
